# fly.toml app configuration file generated for part3phonebook on 2024-01-04T18:47:37+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "part3phonebook"
primary_region = "syd"

[build]

[env]
  PORT = "3001" 

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
